package com.damian.healthchef.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFFEECD6F)
val md_theme_light_onPrimary = Color(0xFF020300)
val md_theme_light_primaryContainer = Color(0xFFD8E2FF)
val md_theme_light_onPrimaryContainer = Color(0xFFDAA12E)
val md_theme_light_secondary = Color(0xFFC0850C)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFCC972B)
val md_theme_light_onSecondaryContainer = Color(0xFF00210E)
val md_theme_light_tertiary = Color(0xFF00658A)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFC4E7FF)
val md_theme_light_onTertiaryContainer = Color(0xFF001E2C)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFF020300)
val md_theme_light_onBackground = Color(0xFF1B1B1F)
val md_theme_light_surface = Color(0xFFEECD6F)
val md_theme_light_onSurface = Color(0xFF1B1B1F)
val md_theme_light_surfaceVariant = Color(0xFFE1E2EC)
val md_theme_light_onSurfaceVariant = Color(0xFF44474F)
val md_theme_light_outline = Color(0xFF74777F)
val md_theme_light_inverseOnSurface = Color(0xFFF2F0F4)
val md_theme_light_inverseSurface = Color(0xFF303033)
val md_theme_light_inversePrimary = Color(0xFFADC6FF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFFEECD6F)
val md_theme_light_outlineVariant = Color(0xFFC4C6D0)
val md_theme_light_scrim = Color(0xFF000000)

val Black40 = Color(0xFF020300)
val Gold40 = Color(0xFFEECD6F)
val Gold80 = Color(0xFFC0850C)
val White40 = Color(0xFFFFFFFF)